# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib mrvcr, .registration = TRUE
NULL

lm_fit_rust <- function(y, x, offset, pet, method, tol, singular_ok, calc_se) .Call(wrap__lm_fit_rust, y, x, offset, pet, method, tol, singular_ok, calc_se)

wlm_fit_rust <- function(y, x, weights, offset, pet, method, tol, singular_ok, calc_se) .Call(wrap__wlm_fit_rust, y, x, weights, offset, pet, method, tol, singular_ok, calc_se)

glm_fit_rust <- function(y, x, weights, offset, family, link, pet, method, param, max_iter, tol, singular_ok, calc_se) .Call(wrap__glm_fit_rust, y, x, weights, offset, family, link, pet, method, param, max_iter, tol, singular_ok, calc_se)

vcm_fit_rust <- function(y, x, v, pet, method) .Call(wrap__vcm_fit_rust, y, x, v, pet, method)

vcm_zzt_fit_rust <- function(y, x, z, pet, method) .Call(wrap__vcm_zzt_fit_rust, y, x, z, pet, method)

mvcm_fit_rust <- function(y, x, pet) .Call(wrap__mvcm_fit_rust, y, x, pet)

lmm_fit_rust <- function(`_y`, `_x`, `_z`, `_pet`) .Call(wrap__lmm_fit_rust, `_y`, `_x`, `_z`, `_pet`)

glmm_fit_rust <- function(`_y`, `_x`, `_family`, `_method`) .Call(wrap__glmm_fit_rust, `_y`, `_x`, `_family`, `_method`)

arima_fit_rust <- function(`_y`, `_p`, `_d`, `_q`, `_pet`) .Call(wrap__arima_fit_rust, `_y`, `_p`, `_d`, `_q`, `_pet`)

# nolint end
