# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib mrvcr, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

# ---- from kron_mv.cpp ----
#' @export
kron_mv <- function(sigmas, Vs, x) {
    .Call(`_mrvcr_kron_mv`, sigmas, Vs, x)
}

# ---- from rcpp_fit_mrvc.cpp ----
#' @export
rcpp_fit_mrvc <- function(vecY, n, d, vecX, p, Vlist, reml, algo, tol, max_iter) {
    .Call(`_mrvcr_rcpp_fit_mrvc`, vecY, n, d, vecX, p, Vlist, reml, algo, tol, max_iter)
}

